#PBS -N Cri
#PBS -j eo
#PBS -e /var/www/html/bindres/results/$random/bindres.err
#PBS -q batch
#PBS -l nodes=1:ppn=4
# This jobs working directory is set below

echo Running on host `hostname`
echo Time is `date`

cd /scratch/working/$random
echo Working directory is `pwd`
touch /scratch/working/$random/made_it

# run the job
/var/www/html/bindres/scripts/bindres.sh
cp /scratch/working/$random/* /var/www/html/bindres/results/$random/.
